theme: jekyll-theme-dinky
title: Keizaal
description: Keizaal is a simple modlist that seeks to enhance and expand on Skyrim without compromising Bethesdaâ€™s original vision that we all fell in love with back in 2011.
show_downloads: true
wabbajack:
  wabbajack_url: https://www.wabbajack.org/#/
github:
  modlistrelases_url: https://github.com/EzioTheDeadPoet/SME-FT-/releases
  modlist_url: https://github.com/EzioTheDeadPoet/Tales-from-the-Northern-Lands/releases/download/v1.0/Tales.from.Skyrim.s.Holds.wabbajack
pages:
  mainpage_url: https://pierredespereaux.github.io/Keizaal/
  installationguide_url: https://pierredespereaux.github.io/Keizaal/INSTALLATIONGUIDE.html
  changelog_url: https://pierredespereaux.github.io/Keizaal//CHANGELOG.html
reshade:
  license: https://eziothedeadpoet.github.io/Tales-from-the-Northern-Lands/ReShade/RESHADELICENSE.html
